version: '3'
services:
  web:
    image: nginx:1.17.10-alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www/
  app:
    build: ./php
    depends_on:
      - mysql
    volumes:
      - ../:/var/www/
  mysql:
    image: mysql:8.0.19
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: gearArchive
      MYSQL_ROOT_PASSWORD: gearArchive
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
  workspace:
    build: ./workspace
    volumes:
     - ../:/var/www/
    ports:
     - "22:22"
    extra_hosts:
      - "gear-archive:192.168.1.10"